"""empty message

Revision ID: 3615c2aeca7d
Revises: 
Create Date: 2024-09-19 16:47:28.412809

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3615c2aeca7d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("motion_pictures", schema=None) as batch_op:
        batch_op.add_column(sa.Column("overview", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("motion_pictures", schema=None) as batch_op:
        batch_op.drop_column("overview")

    # ### end Alembic commands ###
